### ISSUE TITLE
04.WebControlLED网页点击on按钮或OFF按钮网页就变乱码了，请问你做试验也是这样？

### ISSUE THREAD

**Issue by armxu** [imliubo/makingfunxyz-esp8266#1]
![image](https://user-images.githubusercontent.com/19689139/53390807-62327c00-39cf-11e9-92e0-12aecc6f0302.png)
点击按钮后出现的网页。
![image](https://user-images.githubusercontent.com/19689139/53390816-6c547a80-39cf-11e9-8478-c1d8e95f6224.png)
另外请问你的04.WebControlLED例程里是不是没有串口初始化，我自己加了才有正确的串口输出。

**Comment by imliubo** [comment]
Hi,
可以修改一下app->user->user_webserver.c->325L:
`                ret = spi_flash_read(508*4096, (uint32 *)index, index_size);  // start address:0x10000 + 0xC0000`
乱码应该是第二次返回的网页数据不对，就是这个地方读取的位置不对，你可以修改试一下，500修改成508，这个数值取决于你烧录网页的地址。
Have a nice day!

**Comment by imliubo** [comment]
@armxu 
Hi,
可以修改一下app->user->user_webserver.c->325L:
` ret = spi_flash_read(508*4096, (uint32 *)index, index_size); // start address:0x10000 + 0xC0000`
乱码应该是第二次返回的网页数据不对，就是这个地方读取的位置不对，你可以修改试一下，500修改成508，这个数值取决于你烧录网页的地址。
Have a nice day!

**Comment by armxu** [comment]
谢谢你及时的回复。这个问题我应该仔细阅读程序就能解决。非常感谢！
