### ISSUE TITLE
请教一个问题SDK V3.0如何选择SPI_SIZE_MAP?

### ISSUE THREAD

**Issue by armxu** [imliubo/makingfunxyz-esp8266#2]
imliubo：
   你好！
   谢谢你分享的代码，让我学习你的代码。
   请教一个问题SDK V3.0如何选择SPI_SIZE_MAP?
![image](https://user-images.githubusercontent.com/19689139/53399448-f825d100-39e6-11e9-8a53-3f9858cdc965.png)

                                                                   谢谢！

**Comment by imliubo** [comment]
Hi:
如果你使用Linux交叉编译的话可能会注意到这个地方，其实这个参数不光是实际Flash大小决定的，其中的代码分布也决定了这个参数，就是我们烧写代码时几个bin文件的烧录地址，贴几张图相信你一看就懂了。
![esp8266_flashsize](https://user-images.githubusercontent.com/26544331/53459322-4f25b780-3a74-11e9-863d-311a3cc02ef0.png)
![image](https://user-images.githubusercontent.com/26544331/53459182-d1fa4280-3a73-11e9-87f4-c75ead8768f7.png)
![image](https://user-images.githubusercontent.com/26544331/53459198-e1798b80-3a73-11e9-88d9-cf812b2b597b.png)
这里如果你的模组的Flash大小是32Mbit既4MB的话，一般选择4或6都可以，但是下载的时候注意选择32Mbit或32Mbit-C1。
希望可以帮助到你。
Have nice day!

**Comment by armxu** [comment]
谢谢你的回复和帮助。



armxu@126.com
 
发件人： IAMLIUBO
发送时间： 2019-02-27 09:45
收件人： imliubo/makingfunxyz-esp8266
抄送： armxu; Author
主题： Re: [imliubo/makingfunxyz-esp8266] 请教一个问题SDK V3.0如何选择SPI_SIZE_MAP? (#2)
Hi:
如果你使用Linux交叉编译的话可能会注意到这个地方，其实这个参数不光是实际Flash大小决定的，其中的代码分布也决定了这个参数，就是我们烧写代码时几个bin文件的烧录地址，贴几张图相信你一看就懂了。



这里如果你的模组的Flash大小是32Mbit既4MB的话，一般选择4或6都可以，但是下载的时候注意选择32Mbit或32Mbit-C1。
希望可以帮助到你。
Have nice day!

**Comment by imliubo** [comment]
Hi,
如果没有别的问题，我这里就先close了。
Have nice day!
