### ISSUE TITLE
QUESTIONS

### ISSUE THREAD

**Issue by wuqian1013** [imliubo/makingfunxyz-esp8266#4]
**Describe the bug or compile error**
Traceback (most recent call last):
  File "E:/intelligence/makingfunxyz-esp8266-master/makingfunxyz-esp8266-NONOS/06.TCP_UDP_Server_Client/TCP_Server.py", line 9, in <module>
    tcpServer.bind(ADDR)
OSError: [WinError 10049] 在其上下文中，该请求的地址无效。

**environment**
1. Desktop OS(windows、linux or macOS): windows
2. IDE(ai-thinker eclipse IDE、Linux GCC Cross compilation or espressif VirtualBox environment): aithinker
3. SDK Version(NonOS Vx.x.x or RTOS Vx.x.x): nonOS
4. Hardware platform and flash size(NodeMCU、ESP8266-DevKitC or others/2MB、4MB or more):NODEMCU 
5. example(the example No.): 

**Expected behavior**

**Screenshots**

**Additional [context**]()

**Comment by imliubo** [comment]
Hi，
很抱歉没有在python脚本中写注释，其实这个问题是跟本机IP有关的，在文章中有叙述，如下：
![image](https://user-images.githubusercontent.com/26544331/54822572-437a8900-4ce0-11e9-8f92-49f0d965ec68.png)
可以仔细查看一下文章哦~
[传送门](https://zhuanlan.zhihu.com/p/51665508)
修改以后可以再尝试运行一下，有问题可以再继续提交issue。
Have a nice day!

**Comment by imliubo** [comment]
Hi,
如果没什么问题，我这边先close了，如果还有问题可以reopen~
Have a nice day!
