### ISSUE TITLE
Q

### ISSUE THREAD

**Issue by wuqian1013** [imliubo/makingfunxyz-esp8266#6]
**Describe the problem you are experiencing**

直显示waiting for connection，串口并没有什么反应

**Additional context**

-

**Comment by imliubo** [comment]
Hi，
    请增加更多描述，比如ESP8266是作为client还是server，还有“串口并没有什么反应”指的是什么都没打印？还是没有打印预期的内容。More detail I need~

Have a nice day!

**Comment by wuqian1013** [comment]
ESP8266是作为client,串口什么也不显示，空白，

**Comment by imliubo** [comment]
Hi,
    如果是刚入门开始学习ESP8266建议可以先去看一下这个视频，[超级萌新入门ESP8266必看视频](https://www.bilibili.com/video/av49650882/)，如果还没有解决此问题可以加群一起讨论。

**Comment by wuqian1013** [comment]
好的，谢谢☺️------------------ 原始邮件 ------------------
发件人: "IAMLIUBO"<notifications@github.com>
发送时间: 2019年4月23日(星期二) 上午9:15
收件人: "imliubo/makingfunxyz-esp8266"<makingfunxyz-esp8266@noreply.github.com>;
抄送: "wuqian1013"<970173724@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [imliubo/makingfunxyz-esp8266] Q (#6)



Hi,
 如果是刚入门开始学习ESP8266建议可以先去看一下这个视频，超级萌新入门ESP8266必看视频，如果还没有解决此问题可以加群一起讨论。
 
&mdash;
